### PR TITLE
[NOT READY] fix some linux compile issues with CEF 2171

### PR DESCRIPTION
**Pull request by jasonsanjose**
This PR fixes some compile issues, but I'm still seeing errors that I haven't been able to resolve:

```
jasonsj@ubuntu:~/Github/brackets-shell$ grunt build
Running "build" task

Running "build-linux" task
>> out/Release/obj.target/Brackets/appshell/cefclient_gtk.o: In function `main':
>> cefclient_gtk.cpp:(.text+0x7cc): undefined reference to `CefExecuteProcess(CefMainArgs const&, CefRefPtr<CefApp>, void*)'
>> cefclient_gtk.cpp:(.text+0xb99): undefined reference to `CefInitialize(CefMainArgs const&, CefStructBase<CefSettingsTraits> const&, CefRefPtr<CefApp>, void*)'
>> cefclient_gtk.cpp:(.text+0xff1): undefined reference to `CefBrowserHost::CreateBrowser(CefWindowInfo const&, CefRefPtr<CefClient>, CefStringBase<CefStringTraitsUTF16> const&, CefStructBase<CefBrowserSettingsTraits> const&, CefRefPtr<CefRequestContext>)'
>> out/Release/obj.target/libcef_dll_wrapper/libcef_dll/wrapper/libcef_dll_wrapper.o: In function `CefShutdown()':
>> libcef_dll_wrapper.cc:(.text+0x2ac): undefined reference to `CefCppToC<CefCompletionHandlerCppToC, CefCompletionHandler, _cef_completion_handler_t>::DebugObjCt'
>> libcef_dll_wrapper.cc:(.text+0x365): undefined reference to `CefCToCpp<CefDOMEventCToCpp, CefDOMEvent, _cef_domevent_t>::DebugObjCt'
>> libcef_dll_wrapper.cc:(.text+0x38a): undefined reference to `CefCppToC<CefDOMEventListenerCppToC, CefDOMEventListener, _cef_domevent_listener_t>::DebugObjCt'
>> libcef_dll_wrapper.cc:(.text+0x952): undefined reference to `CefCppToC<CefTraceClientCppToC, CefTraceClient, _cef_trace_client_t>::DebugObjCt'
>> out/Release/obj.target/libcef_dll_wrapper/libcef_dll/wrapper/libcef_dll_wrapper.o: In function `CefGetTraceBufferPercentFullAsync()':
>> libcef_dll_wrapper.cc:(.text+0x12a9): undefined reference to `cef_get_trace_buffer_percent_full_async'
>> out/Release/obj.target/libcef_dll_wrapper/libcef_dll/wrapper/libcef_dll_wrapper.o: In function `CefEndTracingAsync()':
>> libcef_dll_wrapper.cc:(.text+0x12c2): undefined reference to `cef_end_tracing_async'
>> out/Release/obj.target/libcef_dll_wrapper/libcef_dll/wrapper/libcef_dll_wrapper.o: In function `CefCppToC<CefTraceClientCppToC, CefTraceClient, _cef_trace_client_t>::Wrap(CefRefPtr<CefTraceClient>)':
>> libcef_dll_wrapper.cc:(.text._ZN9CefCppToCI20CefTraceClientCppToC14CefTraceClient19_cef_trace_client_tE4WrapE9CefRefPtrIS1_E[_ZN9CefCppToCI20CefTraceClientCppToC14CefTraceClient19_cef_trace_client_tE4WrapE9CefRefPtrIS1_E]+0x4f): undefined reference to `CefTraceClientCppToC::CefTraceClientCppToC(CefTraceClient*)'
>> out/Release/obj.target/libcef_dll_wrapper/libcef_dll/ctocpp/domnode_ctocpp.o: In function `CefCppToC<CefDOMEventListenerCppToC, CefDOMEventListener, _cef_domevent_listener_t>::Wrap(CefRefPtr<CefDOMEventListener>)':
>> domnode_ctocpp.cc:(.text._ZN9CefCppToCI25CefDOMEventListenerCppToC19CefDOMEventListener24_cef_domevent_listener_tE4WrapE9CefRefPtrIS1_E[_ZN9CefCppToCI25CefDOMEventListenerCppToC19CefDOMEventListener24_cef_domevent_listener_tE4WrapE9CefRefPtrIS1_E]+0x4f): undefined reference to `CefDOMEventListenerCppToC::CefDOMEventListenerCppToC(CefDOMEventListener*)'
>> collect2: error: ld returned 1 exit status
>> make: * [out/Release/Brackets] Error 1
Warning: Task "build-linux" failed. Use --force to continue.

Aborted due to warnings.

```

The closest thing I've found on the forums is http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=10786, but making the suggested change to `appshell.gyp`, running `grunt setup` and `grunt build` again doesn't improve anything.

Another notable bug with 2171 is that the sample `cefclient` doesn't build with Ubuntu 14.04 https://code.google.com/p/chromiumembedded/issues/detail?id=1430. It's patched later in build 3.2171.1941,

### CODE REVIEW

**Comment by busykai** [comment]
@ingorichter, what is the difference between `isReallyClosing` (file-level in `cefclient_gtk.cpp`) and `ClientHandler::m_quitting`? Aren't they serving the same purpose -- to mark the second call to close handler as actually allowing to close. Pardon if it's obvious, just starting here.

**Comment by nethip** [comment]
@busykai `isReallyClosing` was added to experiment and solve the crash on quit on Linux. I think `isReallyClosing` is used to figure out if a call to `destroy()` orginated from `terminate()` (in which case `CefMessageLoop` is explicitly called). This should eventually be moved to `ClientHandler::OnBeforeClose()`(like how it happens on other platforms). Please see my comments above for a more detailed explanation.

**Comment by busykai** [comment]
thanks, @nethip! so i've gotten to the point where the shell would quit from the message loop, but it started to hang in shutdown. looking at to threads state in the hang, i found that `nodeReadThread` was in the blocking `read`, rewrote it to use `select`, now the thread quits, but the hang still appears. apparently, the shutdown waits for the renderer thread. here is the state of threads and the main thread stack trace:

```
(gdb) info threads
  Id   Target Id         Frame 
  8    Thread 0x7fb9fef14700 (LWP 15499) "dconf worker" 0x00007fba0a523bad in poll ()
    at ../sysdeps/unix/syscall-template.S:81
  7    Thread 0x7fb9fe713700 (LWP 15500) "gdbus" 0x00007fba0a523bad in poll ()
    at ../sysdeps/unix/syscall-template.S:81
  6    Thread 0x7fb9fce7a700 (LWP 15501) "sandbox_ipc_thr" 0x00007fba0a523bad in poll ()
    at ../sysdeps/unix/syscall-template.S:81
  5    Thread 0x7fb9fbe78700 (LWP 15504) "inotify_reader" 0x00007fba0a528823 in select ()
    at ../sysdeps/unix/syscall-template.S:81
  4    Thread 0x7fb9ec944700 (LWP 15545) "Blink Heap Mark" pthread_cond_wait@@GLIBC_2.3.2
    () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7fb9ec143700 (LWP 15546) "Blink Heap Mark" pthread_cond_wait@@GLIBC_2.3.2
    () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7fb9eb942700 (LWP 15547) "Blink GC Sweepe" pthread_cond_wait@@GLIBC_2.3.2
    () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
* 1    Thread 0x7fba1075ca00 (LWP 15498) "Brackets" 0x00007fba0ad1f66b in pthread_join (
    threadid=140436788717312, thread_return=0x0) at pthread_join.c:92
```
```
(gdb) where 
#0  0x00007fba0ad1f66b in pthread_join (threadid=140436788717312, thread_return=0x0)
    at pthread_join.c:92
#1  0x00007fba0cdbed5f in base::PlatformThread::Join(base::PlatformThreadHandle) ()
   from /home/kai/src/brackets-shell/out/Release/lib/libcef.so
#2  0x00007fba0cdc26a0 in base::SimpleThread::Join() ()
   from /home/kai/src/brackets-shell/out/Release/lib/libcef.so
#3  0x00007fba0eed6529 in content::RenderSandboxHostLinux::~RenderSandboxHostLinux() ()
   from /home/kai/src/brackets-shell/out/Release/lib/libcef.so
#4  0x00007fba0eed6575 in Singleton<content::RenderSandboxHostLinux, DefaultSingletonTraits<content::RenderSandboxHostLinux>, content::RenderSandboxHostLinux>::OnExit(void*) ()
   from /home/kai/src/brackets-shell/out/Release/lib/libcef.so
#5  0x00007fba0cd688b0 in base::AtExitManager::ProcessCallbacksNow() ()
   from /home/kai/src/brackets-shell/out/Release/lib/libcef.so
#6  0x00007fba0cd68803 in base::AtExitManager::~AtExitManager() ()
   from /home/kai/src/brackets-shell/out/Release/lib/libcef.so
#7  0x00007fba0f51acf6 in content::ContentMainRunnerImpl::Shutdown() ()
   from /home/kai/src/brackets-shell/out/Release/lib/libcef.so
#8  0x00007fba0cc9e053 in CefContext::FinalizeShutdown() ()
   from /home/kai/src/brackets-shell/out/Release/lib/libcef.so
#9  0x00007fba0cc9daaf in CefShutdown() ()
   from /home/kai/src/brackets-shell/out/Release/lib/libcef.so
#10 0x0000000000433654 in CefShutdown() ()
#11 0x000000000042f574 in main ()
```
I don't have much knowledge of CEF/Chromium internals, so learning as I go. I wonder where the renderer thread went...

**Comment by nethip** [comment]
Thanks @busykai for looking into this. Sure this is a great learning experience for all of us. In case you didn't know, Brackets uses CEF3 which has a multi-process architecture. All of the java script execution happens in a different process called *render process*. The name of the *render process* for **Brackets** is again **Brackets** on Linux (that is why you see more than one **Brackets** processes in the Activity Monitor). So I am not sure if render thread is what the main thread is waiting one. Is it possible for you to figure out which thread the main thread is waiting on?

While I was experimenting on this branch I found out that, if I call `startNodeProcess()` before `CefInitialize()`, this is taking away the crash. But as @ingorichter mentioned, this means that, if there is any issue with the main **Brackets** process, we might end up with an orphan (node) process.  

@ingorichter I have a question on calling `startNodeProcess()` before `CefInitialize()`.Will the `ping pong` logic that we had implemented to check if both are alive take care of the `orphan process` situation, in case the parent dies before the child? 

And from the above call stack do we suspect anything with disabling sandboxing?

**Comment by ingorichter** [comment]
I don't think that the `ping pong` logic takes care of orphaned threads. I still think it's the best solution to wait before calling `startNodeProcess` to avoid this orphan situation. I don't know how likely this will happen, but this was working before and we should figure out what made it stop working.
Sandboxing was never enabled in our builds. We have explicitly turned it off. It might be good or bad. ;-)
As an experiment, we could try to not start the node process at all to see if this has any impact on the shutdown of Brackets. This way we could narrow the scope at bit. What do you think?

**Comment by nethip** [comment]
@ingoritcher If the ping pong does not take care of the orphan process problem then we should still wait before calling startNodeProcess. 

About not calling startNodeProcess, I did that and it took away the crash. Brackets would terminate gracefully. I am pretty much sure it has something to do with statNodeProcess itself. Either the thread or the way we are forking.

**Comment by jasonsanjose** [comment]
Closing. Will create a new PR.

**Comment by jasonsanjose** [comment]
Updated PR with cleaned up branch here https://github.com/adobe/brackets-shell/issues/499
