### PR TITLE
Updated gyp

### PR DESCRIPTION
**Pull request by ficristo**
This is necessary to support newer compiler (in my case VS2015).
I simply copied the upstream source to the gyp folder but I've excluded the gyp/test folder from the commit.

### CODE REVIEW

**Comment by ficristo** [comment]
@nethip @jasonsanjose 
I know this will be PITA to review but would be awesome if someone could take a look.
If you think that updating gyp is better done by someone of the Brackets team let me know.
Thank you.

**Comment by ingorichter** [comment]
Builds fine on OSX for me. @ficristo are you on Windows? Anybody here to build and smoke test the Linux build? I can do it in the evening, if nobody is available.

**Comment by ficristo** [comment]
@ingorichter I've tested on Windows 7.

**Comment by ficristo** [comment]
Finally I was able to set a VM with Linux.
@nethip @ingorichter Which branch should I test for Linux?

**Comment by nethip** [comment]
Currently Linux builds are getting spawned from linux-1547

**Comment by ficristo** [comment]
I tested on that branch with an updated gyp and seems to works.
I needed only to remove `python2` from this command `gypCommand = "bash -c 'python2 gyp/gyp --depth=.'";` in `tasks/setup.js`.

**Comment by ficristo** [comment]
With the last commit I can create the project on linux too.

**Comment by ficristo** [comment]
@nethip @ingorichter 
Now that version 1.7 has been released, is there any chance that you can review my PRs?

**Comment by nethip** [comment]
LGTM. I would build this branch on VS2010 as well before merging in.

Good job @ficristo . Quite a no of changes actually!

**Comment by nethip** [comment]
@ficristo I am getting following errors when I am building using VS2013.

```
2>appshell\appshell_extensions_win.cpp(429): error C2220: warning treated as error - no 'object' file generated
2>appshell\appshell_extensions_win.cpp(429): warning C4996: 'GetVersionExW': was declared deprecated
2>          C:\Program Files (x86)\Windows Kits\8.1\Include\um\sysinfoapi.h(442) : see declaration of 'GetVersionExW'
2>  resource_util_win.cpp
2>  cef_dark_aero_window.cpp
2>  cef_dark_window.cpp
2>  cef_host_window.cpp
2>appshell\cef_dark_aero_window.cpp(60): error C2220: warning treated as error - no 'object' file generated
2>appshell\cef_dark_aero_window.cpp(60): warning C4996: 'GetVersionExW': was declared deprecated
2>          C:\Program Files (x86)\Windows Kits\8.1\Include\um\sysinfoapi.h(442) : see declaration of 'GetVersionExW'
```

**Comment by ficristo** [comment]
The `GetVersionExW` warnings should be fixed by: https://github.com/adobe/brackets-shell/pull/549

**Comment by nethip** [comment]
Thanks @ficristo

**Comment by nethip** [comment]
@ficristo After merging your PRs I am getting following linker errors, upon building master. 
```
2>appshell_extensions_win.obj : error LNK2019: unresolved external symbol __imp__IsTextUnicode@12 referenced in function "bool __cdecl GetBufferAsUTF8(struct UTFValidationState &)" (?GetBufferAsUTF8@@YA_NAAUUTFValidationState@@@Z)
2>appshell_extensions_win.obj : error LNK2019: unresolved external symbol __imp__RegCloseKey@4 referenced in function "class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > __cdecl GetPathToLiveBrowser(void)" (?GetPathToLiveBrowser@@YA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@XZ)
2>cef_registry.obj : error LNK2001: unresolved external symbol __imp__RegCloseKey@4
2>appshell_extensions_win.obj : error LNK2019: unresolved external symbol __imp__RegOpenKeyExW@20 referenced in function "class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > __cdecl GetPathToLiveBrowser(void)" (?GetPathToLiveBrowser@@YA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@XZ)
2>cef_registry.obj : error LNK2001: unresolved external symbol __imp__RegOpenKeyExW@20
2>appshell_extensions_win.obj : error LNK2019: unresolved external symbol __imp__RegQueryValueExW@24 referenced in function "class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > __cdecl GetPathToLiveBrowser(void)" (?GetPathToLiveBrowser@@YA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@XZ)
2>cef_registry.obj : error LNK2001: unresolved external symbol __imp__RegQueryValueExW@24
2>cef_registry.obj : error LNK2019: unresolved external symbol __imp__RegCreateKeyExW@36 referenced in function "bool __cdecl WriteRegistryInt(wchar_t const *,wchar_t const *,int)" (?WriteRegistryInt@@YA_NPB_W0H@Z)
2>cef_registry.obj : error LNK2019: unresolved external symbol __imp__RegSetValueExW@24 referenced in function "bool __cdecl WriteRegistryInt(wchar_t const *,wchar_t const *,int)" (?WriteRegistryInt@@YA_NPB_W0H@Z)
2>Release\Brackets.exe : fatal error LNK1120: 6 unresolved externals

```

**Comment by nethip** [comment]
I am on VS 2013.

**Comment by ingorichter** [comment]
@nethip what VS version does the build machine use? Do we have a followup issue that addresses the build failure?

**Comment by nethip** [comment]
@ingorichter Build machine is configured with VS2010. I think we need to build this on VS 2010 and see if works. I can ask RE to fire a build to check if it is building fine.

VS 2015 build is going fine actually. It is just VS2013 that is failing.

**Comment by ingorichter** [comment]
@nethip perhaps we should update the build machines to use VS2015. Which Xcode version do we use on the build machines? 7.3?

**Comment by nethip** [comment]
@ingorichter Sure! We need to inform then RE about it. Mac build machine is configured with 10.9 and XCode 5.0. I think upgrading to VS 2015 is a lot easier. For Mac, the entire system needs to be upgraded. I will ping RE about it.

Regarding the build failure. Really weird! If I manually add `advapi32.lib` to linker settings in VS 2013, it builds fine.

**Comment by nethip** [comment]
@ingorichter @ficristo I have raised a PR for this at https://github.com/adobe/brackets-shell/pull/560 let me know if it looks good.
